import { useRef, useState } from 'react'
import { Cloud, Download, LogOut, RefreshCw, Upload } from 'lucide-react'
import { useApp } from '../lib/AppContext'
export default function SettingsPage(){
  const {state,setTheme,apiConfigured,signedIn,syncStatus,login,setup,logout,syncNow,exportBackup,importBackup,reset}=useApp();const file=useRef<HTMLInputElement>(null)
  const [mode,setMode]=useState<'login'|'setup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[message,setMessage]=useState('')
  const submit=async()=>{setMessage('');try{if(mode==='login')await login(email,password);else await setup(email,password,code);setMessage('Cloud sync connected.')}catch(e:any){setMessage(e.message||'Could not connect.') }}
  return <div className="page"><header className="simple-header"><span className="eyebrow">Settings</span><h1>Storage and preferences</h1><p>Daily use should stay simple. The technical setup lives here so it stays out of your study flow.</p></header>
    <section className="panel settings-section"><h2>Appearance</h2><div className="segmented">{(['light','dark','system'] as const).map(t=><button key={t} className={state.settings.theme===t?'active':''} onClick={()=>setTheme(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div></section>
    <section className="panel settings-section"><div className="settings-title"><div><h2>Cloud sync</h2><p>Your progress is always stored locally first in IndexedDB. Cloud sync is optional.</p></div><span className={`status-badge ${syncStatus}`}>{signedIn?syncStatus:'local only'}</span></div>{!apiConfigured?<div className="notice">This build has no backend URL configured. Local storage and JSON backup still work.</div>:signedIn?<div className="button-row"><button className="button secondary" onClick={()=>void syncNow()}><RefreshCw size={16}/>Sync now</button><button className="button ghost" onClick={logout}><LogOut size={16}/>Sign out</button></div>:<div className="auth-box"><div className="segmented small"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='setup'?'active':''} onClick={()=>setMode('setup')}>First-time setup</button></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='setup'&&<label>Owner setup code<input type="password" value={code} onChange={e=>setCode(e.target.value)}/></label>}<button className="button" onClick={()=>void submit()}><Cloud size={16}/>{mode==='login'?'Sign in and sync':'Create owner account'}</button>{message&&<p className="form-message">{message}</p>}</div>}</section>
    <section className="panel settings-section"><h2>Backup</h2><p>Cloud or not, a portable backup is useful. Exporting does not interrupt automatic local saving.</p><div className="button-row"><button className="button secondary" onClick={exportBackup}><Download size={16}/>Export backup</button><button className="button secondary" onClick={()=>file.current?.click()}><Upload size={16}/>Import backup</button><input ref={file} type="file" accept="application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(f)await importBackup(f)}}/></div></section>
    <section className="panel settings-section danger-zone"><h2>Reset local progress</h2><p>This clears task completion on this device and will sync the reset if cloud sync is connected.</p><button className="button danger" onClick={()=>{if(confirm('Reset all study progress?'))void reset()}}>Reset progress</button></section>
  </div>
}
